### ISSUE TITLE
how to add Chinese support?

### ISSUE THREAD

**Issue by SeekPoint** [philipperemy/google-news-scraper#16]

**Comment by philipperemy** [comment]
@loveJasmine do you have Google in China?

Can you provide me with a similar URL for Chinese:

https://www.google.co.jp/search?q=エクソンモービル&hl=ja&source=lnt&tbs=cdr%3A1%2Ccd_min%3A2010%2Ccd_max%3A2020&tbm=nws&start=0

Thanks.

**Comment by SeekPoint** [comment]
https://www.google.com.hk/search?newwindow=1&safe=strict&source=hp&ei=HydCX5CTIcGsmAXrgbXwCw&q=%E7%81%AB%E6%98%9F%E6%8E%A2%E7%B4%A2%E8%AE%A1%E5%88%92&oq=%E7%81%AB%E6%98%9F%E6%8E%A2%E7%B4%A2%E8%AE%A1%E5%88%92&gs_lcp=CgZwc3ktYWIQAzICCABKBQgJEgExSgUIChIBMVDRDljRDmDLGmgBcAB4AIABkQGIAZEBkgEDMC4xmAEAoAECoAEBqgEHZ3dzLXdperABAA&sclient=psy-ab&ved=0ahUKEwjQnuTL8rDrAhVBFqYKHetADb4Q4dUDCAc&uact=5

https://www.google.com.hk/search?newwindow=1&safe=strict&ei=IydCX9rVG6ezmAWaxZXwCg&q=%E4%B8%AD%E5%9B%BD%E7%9C%81%E7%BA%A7%E8%A1%8C%E6%94%BF%E5%8C%BA%E5%88%92%E6%94%B9%E9%9D%A9%E6%8E%A2%E7%B4%A2&oq=%E4%B8%AD%E5%9B%BD&gs_lcp=CgZwc3ktYWIQAxgEMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgIIADICCABKBQgJEgExSgYIChICMTBQvtwBWO3pAWCtgwJoAHAAeACAAc4CiAH7C5IBBzEuNi4yLjGYAQCgAQGqAQdnd3Mtd2l6wAEB&sclient=psy-ab


i can access www.google.com.hk by VPN

**Comment by philipperemy** [comment]
Ok thank you I will publish the Chinese version.

https://www.google.com.hk/search?q=%E7%81%AB%E6%98%9F%E6%8E%A2%E7%B4%A2%E8%AE%A1%E5%88%92&newwindow=1&safe=strict&source=lnms&tbm=nws&sa=X&ved=2ahUKEwiYiuiEgLHrAhXOa94KHYyUCGUQ_AUoAXoECBQQAw&biw=1280&bih=641&dpr=2

**Comment by philipperemy** [comment]
There's a PR that will be available soon here: https://github.com/philipperemy/google-news-scraper/pull/17/files

**Comment by philipperemy** [comment]
On latest master try:

```
python main_no_vpn.py --keywords 中国省级行政区划改革探索 --language cn
```

**Comment by philipperemy** [comment]
Let me know if it does not work.

**Comment by SeekPoint** [comment]
it works! nice job!

**Comment by philipperemy** [comment]
Happy to hear that :)
